# Generated by Django 4.2.16 on 2024-10-29 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0007_remove_achievements_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievements',
            name='slug',
            field=models.SlugField(default=None, unique=True),
        ),
    ]
