# Generated by Django 4.2.16 on 2025-06-09 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0008_achievements_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Commanders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("deleted", models.BooleanField(default=False)),
                ("has_partner", models.BooleanField(default=False)),
                ("is_background", models.BooleanField(default=False)),
                (
                    "colors",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="achievements.colors",
                    ),
                ),
            ],
            options={
                "db_table": "commanders",
            },
        ),
    ]
