# Generated by Django 4.2.16 on 2025-06-18 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0009_commanders"),
    ]

    operations = [
        migrations.AlterField(
            model_name="achievements",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
