# Generated by Django 4.2.16 on 2025-07-27 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_participantachievements_earned_points"),
        ("achievements", "0010_alter_achievements_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="winningcommanders",
            name="colors",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="achievements.colors",
            ),
        ),
        migrations.AlterField(
            model_name="winningcommanders",
            name="participants",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.participants",
            ),
        ),
    ]
