# Generated by Django 4.2.16 on 2025-08-08 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0011_alter_winningcommanders_colors_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AchievementType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("hex_code", models.BinaryField()),
            ],
            options={
                "db_table": "achievement_type",
            },
        ),
        migrations.AddField(
            model_name="achievements",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="achievements",
                to="achievements.achievementtype",
            ),
        ),
    ]
