# Generated by Django 4.2.16 on 2025-08-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0013_seed_achievement_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="achievementtype",
            name="hex_code",
            field=models.CharField(max_length=7),
        ),
    ]
