# Generated by Django 4.2.16 on 2025-08-08 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0011_alter_winningcommanders_colors_and_more"),
        ("achievements", "0013_reconcile_commanders_table"),
    ]

    operations = []
