# Generated by Django 4.2.16 on 2025-08-08 13:03

from django.db import migrations


def seed_types(apps, schema_editor):
    AchievementType = apps.get_model("achievements", "AchievementType")
    seed_data = [
        {"name": "general", "hex_code": b"#D43220"},  # Red
        {"name": "deckbuilding", "hex_code": b"#68D420"},  # Green
        {"name": "legality", "hex_code": b"#C2D420"},  # Yellow
        {"name": "scaleable", "hex_code": b"#8C20D4"},  # Purple
    ]
    for entry in seed_data:
        AchievementType.objects.get_or_create(**entry)


def remove_types(apps, schema_editor):
    AchievementType = apps.get_model("achievements", "AchievementType")
    AchievementType.objects.filter(
        name__in=["general", "deckbuilding", "legality", "scaleable"]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0012_achievementtype_achievements_type"),
    ]
    operations = [
        migrations.RunPython(seed_types, remove_types),
    ]
