# Generated by Django 4.2.16 on 2025-08-08 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0014_merge_20250808_1635"),
        ("achievements", "0016_alter_achievementtype_hex_code"),
    ]

    operations = []
