# Generated by Django 4.2.16 on 2025-08-08 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0017_merge_20250808_1704"),
    ]

    operations = [
        migrations.AddField(
            model_name="achievementtype",
            name="description",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
