# Generated by Django 4.2.16 on 2026-01-07 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0018_achievementtype_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="colors",
            name="mask",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
