# Generated by Django 4.2.16 on 2026-01-07 02:57
from django.db import migrations

COLOR_BITS = {
    "w": 1,  # 00001
    "u": 2,  # 00010
    "b": 4,  # 00100
    "r": 8,  # 01000
    "g": 16,  # 10000
}


def compute_mask(symbol: str) -> int:
    if not symbol:
        return 0

    s = symbol.strip().lower()
    if s == "c":
        return 0

    mask = 0
    for ch in s:
        try:
            mask |= COLOR_BITS[ch]
        except KeyError as e:
            raise ValueError(
                f"Unknown color symbol character: {ch!r} from symbol={symbol!r}"
            ) from e
    return mask


def forwards(apps, schema_editor):
    Color = apps.get_model("achievements", "Colors")

    for color in Color.objects.all().only("id", "symbol"):
        new_mask = compute_mask(color.symbol)
        Color.objects.filter(id=color.id).update(mask=new_mask)


def backwards(apps, schema_editor):
    Color = apps.get_model("achievements", "Colors")
    Color.objects.all().update(mask=0)


class Migration(migrations.Migration):
    dependencies = [
        ("achievements", "0019_colors_mask"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
