# Generated by Django 4.2.16 on 2026-01-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0020_backfill_color_mask"),
    ]

    operations = [
        migrations.AddField(
            model_name="commanders",
            name="is_companion",
            field=models.BooleanField(default=False),
        ),
    ]
