# Generated by Django 4.2.16 on 2026-01-17 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0021_commanders_is_companion"),
    ]

    operations = [
        migrations.AddField(
            model_name="winningcommanders",
            name="commander",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="achievements.commanders",
            ),
        ),
        migrations.AddField(
            model_name="winningcommanders",
            name="companion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="companion",
                to="achievements.commanders",
            ),
        ),
        migrations.AddField(
            model_name="winningcommanders",
            name="partner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="partner",
                to="achievements.commanders",
            ),
        ),
    ]
