# Generated by Django 4.2.16 on 2026-01-21 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_decklists_give_credit"),
        ("achievements", "0022_winningcommanders_commander_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="winningcommanders",
            name="decklist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.decklists",
            ),
        ),
    ]
