# Generated by Django 4.2.16 on 2026-02-02 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0023_winningcommanders_decklist"),
    ]

    operations = [
        migrations.RenameField(
            model_name="colorfactions",
            old_name="colors",
            new_name="color",
        ),
        migrations.RenameField(
            model_name="commanders",
            old_name="colors",
            new_name="color",
        ),
        migrations.RenameField(
            model_name="winningcommanders",
            old_name="colors",
            new_name="color",
        ),
    ]
