# Generated by Django 4.2.16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0025_winningcommanders_store"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScalableTerms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("term_display", models.CharField(max_length=255)),
                ("sort_order", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "scalable_terms",
            },
        ),
        migrations.CreateModel(
            name="AchievementScalableTerms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "achievement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="achievements.achievements",
                    ),
                ),
                (
                    "scalable_term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="achievements.scalableterms",
                    ),
                ),
            ],
            options={
                "db_table": "achievement_scalable_terms",
            },
        ),
    ]
