# Generated by Django 4.2.16

from django.db import migrations, models
import django.db.models.deletion


SCALABLE_TERM_TYPES = [
    "Grouped Terms",
    "Keyword Ability",
    "Batch",
    "Ability Word",
    "Keyword Action",
    "Token Type",
    "Non-Creature Subtype",
    "Player Designation",
]


def seed_scalable_term_types(apps, schema_editor):
    ScalableTermType = apps.get_model("achievements", "ScalableTermType")
    for name in SCALABLE_TERM_TYPES:
        ScalableTermType.objects.get_or_create(name=name)


def reverse_seed(apps, schema_editor):
    ScalableTermType = apps.get_model("achievements", "ScalableTermType")
    ScalableTermType.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0026_scalable_terms_and_bridge"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScalableTermType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
            ],
            options={
                "db_table": "scalable_term_type",
            },
        ),
        migrations.AddField(
            model_name="scalableterms",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="scalable_terms",
                to="achievements.scalabletermtype",
            ),
        ),
        migrations.RunPython(seed_scalable_term_types, reverse_seed),
    ]
