# Generated by Django 4.2.16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0027_scalable_term_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scalableterms",
            name="sort_order",
        ),
    ]
