# Generated by Django 4.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0028_remove_scalableterms_sort_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="scalableterms",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
