# Generated by Django 4.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0029_scalableterms_deleted"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="scalableterms",
            constraint=models.UniqueConstraint(
                condition=models.Q(deleted=False),
                fields=("term_display",),
                name="unique_term_display_when_not_deleted",
            ),
        ),
        migrations.AddConstraint(
            model_name="achievementscalableterms",
            constraint=models.UniqueConstraint(
                fields=("achievement", "scalable_term"),
                name="unique_achievement_scalable_term",
            ),
        ),
    ]
