version: '3.9'

services:
  backend:
    build:
      context: ./tome
    container_name: tome-backend
    command: gunicorn tome.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./tome:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - ALLOWED_HOSTS=localhost,0.0.0.0
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DEBUG=False

  frontend:
    build:
      context: ./tabernacle
    container_name: tabernacle-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: league-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      DB_NAME: league_db
      DB_USER: postgres
      DB_PASSWORD: password

volumes:
  postgres_data:
