# Generated by Django 4.2.16 on 2026-02-07 04:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0013_sessiontoken_edittoken"),
    ]

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                ("external_url", models.URLField()),
                ("discord_channel_id", models.BigIntegerField(unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("deleted", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "stores",
            },
        ),
        migrations.CreateModel(
            name="StoreUserAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("admin", "Admin"), ("staff", "Staff")],
                        default="staff",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stores.store"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "store_user_access",
            },
        ),
        migrations.CreateModel(
            name="StoreParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.participants",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stores.store"
                    ),
                ),
            ],
            options={
                "db_table": "store_participants",
            },
        ),
        migrations.AddConstraint(
            model_name="store",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted", False)),
                fields=("slug",),
                name="unique_active_store_slug",
            ),
        ),
        migrations.AddConstraint(
            model_name="storeuseraccess",
            constraint=models.UniqueConstraint(
                fields=("store", "user"), name="uniq_store_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="storeparticipant",
            constraint=models.UniqueConstraint(
                fields=("store", "participant"), name="uniq_store_participant"
            ),
        ),
    ]
