# Generated by Django 4.2.16 on 2026-02-07 04:10

from django.db import migrations


def create_data(apps, schema_editor):
    StoreModel = apps.get_model("stores", "Store")

    StoreModel.objects.create(
        name="The Money Store",
        slug="moneystore-stage",
        external_url="https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        discord_guild_id=1300613593397727302,
    )
    StoreModel.objects.create(
        name="Mimic's Market",
        slug="mimicsmarket",
        external_url="https://mimicsmarket.com/",
        discord_guild_id=1123750208937938964,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0001_initial"),
    ]

    operations = [migrations.RunPython(create_data)]
