# Generated by Django 4.2.16 on 2026-02-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0002_seed_initial_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="discord_channel_id",
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
