# Generated by Django 4.2.16 on 2026-02-24 14:25

from django.db import migrations


def update_data(apps, schema_editor):
    StoreModel = apps.get_model("stores", "Store")
    Config = apps.get_model("configs", "Config")

    mimic = StoreModel.objects.get(slug="mimicsmarket")
    money = StoreModel.objects.get(slug="moneystore-stage")
    fab = StoreModel.objects.get(slug="fabforge")

    mimic.discord_channel_id = 1203058271620038756
    money.discord_channel_id = 1300613593397727305
    fab.discord_channel_id = 839214668090441728
    mimic.save(update_fields=["discord_channel_id"])
    money.save(update_fields=["discord_channel_id"])
    fab.save(update_fields=["discord_channel_id"])

    def upsert_shop_config(*, store, key, value, name, description):
        Config.objects.update_or_create(
            scope_kind="shop",
            store_id=store.id,
            key=key,
            defaults={
                "value": str(value),
                "name": name,
                "description": description,
            },
        )

    for cap_key, cap_name in [
        ("round_one_cap", "Round One Cap"),
        ("round_two_cap", "Round Two Cap"),
    ]:
        global_row = (
            Config.objects.filter(
                key=cap_key, scope_kind="global", store_id__isnull=True
            )
            .order_by("id")
            .first()
        )

        if global_row:
            global_row.scope_kind = "shop"
            global_row.store_id = mimic.id
            global_row.name = cap_name
            global_row.save(update_fields=["scope_kind", "store_id", "name"])
        else:
            upsert_shop_config(
                store=mimic,
                key=cap_key,
                value=24,
                name=cap_name,
                description=f"Max players allowed in {'Round 1' if cap_key == 'round_one_cap' else 'Round 2'}",
            )

    for store in (fab, money):
        upsert_shop_config(
            store=store,
            key="round_one_cap",
            value=50,
            name="Round One Cap",
            description="Max players allowed in Round 1",
        )
        upsert_shop_config(
            store=store,
            key="round_two_cap",
            value=50,
            name="Round Two Cap",
            description="Max players allowed in Round 2",
        )
    upsert_shop_config(
        store=mimic,
        key="round_day",
        value="Sunday",
        name="Round Day",
        description="The day each week that league occurs",
    )
    upsert_shop_config(
        store=fab,
        key="round_day",
        value="Saturday",
        name="Round Day",
        description="The day each week that league occurs",
    )
    upsert_shop_config(
        store=money,
        key="round_day",
        value="Sunday",
        name="Round Day",
        description="The day each week that league occurs",
    )

    # 4) round start times for all three stores
    for store in (mimic, fab, money):
        upsert_shop_config(
            store=store,
            key="round_one_start",
            value="1:30",
            name="Round One Start",
            description="The start time for round 1",
        )
        upsert_shop_config(
            store=store,
            key="round_two_start",
            value="3:30",
            name="Round Two Start",
            description="The start time for round 2",
        )


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0003_store_discord_channel_id"),
    ]

    operations = [migrations.RunPython(update_data)]
