# Generated by Django 4.2.16 on 2026-02-24 14:25

from django.db import migrations


def update_data(apps, schema_editor):
    StoreModel = apps.get_model("stores", "Store")

    mimic = StoreModel.objects.get(slug="mimicsmarket")
    money = StoreModel.objects.get(slug="moneystore-stage")
    fab = StoreModel.objects.get(slug="fabforge")

    mimic.discord_channel_id = 1203058271620038756
    money.discord_channel_id = 1300613593397727305
    fab.discord_channel_id = 839214668090441728

    mimic.save()
    money.save()
    fab.save()


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0003_store_discord_channel_id"),
    ]

    operations = [migrations.RunPython(update_data)]
