# Generated by Django 4.2.16 on 2025-09-30 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Config",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.SlugField(max_length=64)),
                ("value", models.JSONField()),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scope_kind",
                    models.CharField(
                        choices=[("global", "Global"), ("shop", "Shop")],
                        db_index=True,
                        default="global",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "db_table": "configs",
            },
        ),
    ]
