# Generated by Django 4.2.16 on 2026-02-07 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0002_seed_initial_data"),
        ("configs", "0002_seed_initial_configs"),
    ]

    operations = [
        migrations.AddField(
            model_name="config",
            name="store",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="stores.store",
            ),
        ),
    ]
