# Generated by Django 4.2.16 on 2026-02-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configs", "0003_config_store"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="config",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("scope_kind", "shop"), _negated=True),
                    ("store_id__isnull", False),
                    _connector="OR",
                ),
                name="configs_store_required_for_shop_scope",
            ),
        ),
        migrations.AddConstraint(
            model_name="config",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("scope_kind", "global"), _negated=True),
                    ("store_id__isnull", True),
                    _connector="OR",
                ),
                name="configs_store_null_for_global_scope",
            ),
        ),
    ]
