# Generated by Django 4.2.16 on 2026-02-10 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configs", "0004_config_configs_store_required_for_shop_scope_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="config",
            name="value",
            field=models.TextField(),
        ),
    ]
