name: Dockerized Django Tests

on:
  pull_request:
    branches: ["**"]
  push:
    branches: ["**"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run Docker Compose tests
        run: |
          docker-compose -f docker-compose.yml up --abort-on-container-exit --build