# Generated by Django 4.2.16 on 2025-09-25 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_participants_code"),
        ("sessions_rounds", "0003_pods_submitted"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoundSignups",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.participants",
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sessions_rounds.rounds",
                    ),
                ),
            ],
            options={
                "db_table": "round_signups",
            },
        ),
    ]
