# Generated by Django 4.2.16 on 2025-09-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sessions_rounds", "0004_roundsignups"),
    ]

    operations = [
        migrations.AddField(
            model_name="rounds",
            name="starts_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="sessions",
            name="session_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
