# Generated by Django 4.2.16 on 2025-10-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sessions_rounds", "0006_backfill_time_fields"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="roundsignups",
            constraint=models.UniqueConstraint(
                fields=("round", "participant"), name="uniq_round_participant"
            ),
        ),
    ]
