# Generated by Django 4.2.16 on 2025-06-09 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_participantachievements_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="participantachievements",
            name="earned_points",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
