# Generated by Django 4.2.16 on 2025-09-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_reconcile_earned_points"),
    ]

    operations = [
        migrations.AddField(
            model_name="participants",
            name="code",
            field=models.CharField(default=None, max_length=6, unique=True, null=True),
        ),
        migrations.AddField(
            model_name="participants",
            name="discord_user_id",
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
