# Generated by Django 4.2.16 on 2025-09-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_backfill_codes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participants",
            name="code",
            field=models.CharField(default=None, max_length=6, unique=True),
        ),
    ]
