# Generated by Django 4.2.16 on 2026-01-14 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0018_achievementtype_description"),
        ("users", "0008_alter_participants_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="Decklists",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("url", models.TextField()),
                ("code", models.CharField(editable=False, max_length=10, unique=True)),
                ("deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "decklists",
            },
        ),
        migrations.CreateModel(
            name="DecklistsAchievements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "achievements",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="achievements.achievements",
                    ),
                ),
                (
                    "decklists",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.decklists",
                    ),
                ),
            ],
            options={
                "db_table": "decklists_achievements",
            },
        ),
        migrations.AddField(
            model_name="decklists",
            name="achievement",
            field=models.ManyToManyField(
                related_name="decklists",
                through="users.DecklistsAchievements",
                to="achievements.achievements",
            ),
        ),
        migrations.AddField(
            model_name="decklists",
            name="commander",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="achievements.commanders",
            ),
        ),
        migrations.AddField(
            model_name="decklists",
            name="participant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.participants",
            ),
        ),
    ]
