# Generated by Django 4.2.16 on 2026-01-14 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_decklists_decklistsachievements_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="decklistsachievements",
            old_name="achievements",
            new_name="achievement",
        ),
        migrations.RenameField(
            model_name="decklistsachievements",
            old_name="decklists",
            new_name="decklist",
        ),
    ]
