# Generated by Django 4.2.16 on 2026-01-14 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0018_achievementtype_description"),
        (
            "users",
            "0010_rename_achievements_decklistsachievements_achievement_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="decklists",
            name="companion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="companion_decklists",
                to="achievements.commanders",
            ),
        ),
        migrations.AddField(
            model_name="decklists",
            name="partner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="partner_decklists",
                to="achievements.commanders",
            ),
        ),
        migrations.AlterField(
            model_name="decklists",
            name="commander",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commander_decklists",
                to="achievements.commanders",
            ),
        ),
    ]
