# Generated by Django 4.2.16 on 2026-01-14 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_decklists_companion_decklists_partner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="decklists",
            name="give_credit",
            field=models.BooleanField(default=False),
        ),
    ]
