# Generated by Django 4.2.16 on 2026-02-07 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0002_seed_initial_data"),
        ("users", "0013_sessiontoken_edittoken"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Users",
        ),
        migrations.AddField(
            model_name="participantachievements",
            name="store",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="stores.store",
            ),
        ),
    ]
