# Generated by Django 4.2.16 on 2026-02-18 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_decklists_store"),
    ]

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("email", models.EmailField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("admin", models.BooleanField(default=False)),
                ("deleted", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("password", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "users",
            },
        ),
    ]
