# Generated by Django 4.2.16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0026_scalable_terms_and_bridge"),
        ("users", "0016_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="participantachievements",
            name="scalable_term",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="participant_achievements",
                to="achievements.scalableterms",
            ),
        ),
    ]
