# Generated by Django 4.2.16 on 2026-09-14 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_participants_is_patreon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aversions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('declared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aversions_declared', to='users.participants')),
                ('participant_high', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aversions_as_high', to='users.participants')),
                ('participant_low', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aversions_as_low', to='users.participants')),
            ],
            options={
                'db_table': 'aversions',
            },
        ),
        migrations.AddConstraint(
            model_name='aversions',
            constraint=models.UniqueConstraint(fields=('participant_low', 'participant_high'), name='unique_aversion_pair'),
        ),
        migrations.AddConstraint(
            model_name='aversions',
            constraint=models.CheckConstraint(check=models.Q(('participant_low_id__lt', models.F('participant_high_id'))), name='aversion_low_lt_high'),
        ),
    ]
