name: Django Tests

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14.10
        env:
          POSTGRES_DB: league_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres    
        ports:
          - 5432:5432 
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
          
    env:
      DB_NAME: league_test
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: 127.0.0.1
      DB_TEST_NAME: test_league_test
      DB_PORT: 5432

    steps:

      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install -r tome/requirements.txt

      - name: Run unit tests
        working-directory: tome
        run: python -m pytest --import-mode=append