name: Django Tests

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14.10
        env:
          POSTGRES_DB: league_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres     
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
          
    env:
      DB_NAME: league_test
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: localhost
      DB_TEST_NAME: test_league_test
      DB_PORT: 5432

    steps:

      - name: Check out code
        uses: actions/checkout@v4

      - name: Check DB environment vars
        run: |
          echo "DB_USER=$DB_USER"
          echo "DB_NAME=$DB_NAME"
          echo "DB_PASSWORD=$DB_PASSWORD"
          echo "DB_HOST=$DB_HOST"
          echo "DB_PORT=$DB_PORT"
        env:
          DB_NAME: ${{ env.DB_NAME }}
          DB_USER: ${{ env.DB_USER }}
          DB_PASSWORD: ${{ env.DB_PASSWORD }}
          DB_HOST: ${{ env.DB_HOST }}
          DB_PORT: ${{ env.DB_PORT }}

      
      - name: Switch to Current Branch
        run: git checkout ${{ env.BRANCH }}

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.9.23"

      - name: Install dependencies
        run: | 
          pip install -r tome/requirements.txt

      - name: Wait for Postgres to be ready
        run: |
          until pg_isready -h localhost -p 5432 -U postgres; do
            echo "Waiting for postgres..."
            sleep 1
          done


      - name: Run unit tests
        working-directory: tome
        run: python -m pytest --import-mode=append