name: Dockerized Django Tests

on:
  push:
    branches: ["**"]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DB_NAME: league_db
      DB_USER: postgres
      DB_PASSWORD: test123
      DB_HOST: db
      DB_PORT: 5432
      DJANGO_SECRET_KEY: dummy-secret-for-tests
      DEBUG: false

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.2/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version

      - name: Run Docker Compose tests
        run: |
          docker-compose -f docker-compose.yml up --abort-on-container-exit --build